### ISSUE TITLE
suite is broken MultiClusterModeRunner breaks role test...

### ISSUE THREAD

**Issue by skonto** [typesafehub/mesos-spark-integration-tests#62]
@tnachen could you investigate this?
Some resources are leaking i think... 
https://ci.typesafe.com/job/mit-docker-test-zk-ref/26/console
i didnt see that fail earlier and i tested it before merge...

**Comment by tnachen** [comment]
I think possibly because an executor is still taking up a core, but not quite sure. Does this happen all the time? I don't seem to repro on my end.

**Comment by skonto** [comment]
I have seen it lately in zk based project on jenkins, never seen it happen locally.
Maybe the second dispatcher uses a core for a zombie driver which is still running as a task... i dont know either. Ideally every run in your multidispatcher runner should be isolated. I will try to find out if i can reproduce it on jenkins.
